<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Austral\ToolsBundle\AustralToolsBundle::class => ['all' => true],
    Austral\SecurityBundle\AustralSecurityBundle::class => ['all' => true],
    Austral\EntityBundle\AustralEntityBundle::class => ['all' => true],
    Austral\ListBundle\AustralListBundle::class => ['all' => true],
    Austral\FormBundle\AustralFormBundle::class => ['all' => true],
    Austral\AdminBundle\AustralAdminBundle::class => ['all' => true],
    Austral\EntityFileBundle\AustralEntityFileBundle::class => ['all' => true],
    Austral\EntityTranslateBundle\AustralEntityTranslateBundle::class => ['all' => true],
    Austral\EntitySeoBundle\AustralEntitySeoBundle::class => ['all' => true],
    Austral\WebsiteBundle\AustralWebsiteBundle::class => ['all' => true],
    Austral\ContentBlockBundle\AustralContentBlockBundle::class => ['all' => true],
    Austral\HttpBundle\AustralHttpBundle::class => ['all' => true],
    Austral\FilterBundle\AustralFilterBundle::class => ['all' => true],
    Austral\DesignBundle\AustralDesignBundle::class => ['all' => true],
    Symfony\Bundle\MercureBundle\MercureBundle::class => ['all' => true],
    Austral\EmailBundle\AustralEmailBundle::class => ['all' => true],
    Austral\NotifyBundle\AustralNotifyBundle::class => ['all' => true],
];
